# Generated by Django 4.2.7 on 2024-05-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geolocation", "0002_alter_location_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="country_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
